version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - db
    volumes:
      - ./src:/go/src/app
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    working_dir: /var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  mail:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - ${MAIL_WEB_PORT}:8025
volumes:
  mysql-data:
    driver: local
